// <auto-generated />
namespace ShiNengShiHui.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EntitiesInitial5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntitiesInitial5));
        
        string IMigrationMetadata.Id
        {
            get { return "201708240840457_EntitiesInitial5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
